vibinex/vibi-dpu

README.md

Added instructions to run the application locally and for what it is used

Add setup instructions and description to Readme

---

vibi-dpu/src/bitbucket/auth.rs

Refresh token bug fix

---

vibi-dpu/src/bitbucket/prs.rs
vibi-dpu/src/db/prs.rs
vibi-dpu/src/pubsub/listener.rs

bug fix ablejobs

---

vibi-dpu/src/pubsub/listener.rs

added a log

---

vibi-dpu/src/db/prs.rs
vibi-dpu/src/pubsub/listener.rs

bug fix: removed IVec of value while inserting pr_info

---

vibi-dpu/src/db/prs.rs

add debug logs for ivec

---

vibi-dpu/src/utils/gitops.rs

Filter zero deletion files and hunk

---

vibi-dpu/src/utils/gitops.rs

Please check the action items covered in the PR - 
Deployed on ablejobs through PR #69 
Tested for hunk filter with the following input and output - 
```
diffstr = diff --git a/devprofiler/Cargo.toml b/devprofiler/Cargo.toml
index 8bb580e..009521d 100644
--- a/devprofiler/Cargo.toml
+++ b/devprofiler/Cargo.toml
@@ -4 +3,0 @@ version = "0.1.1"
-edition = "2021"
@@ -13,7 +11,0 @@ categories = ["command-line-utilities"]
-
-# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
-
-[dependencies]
-git2 = {version = "0.15", default-features = false, features= ["vendored-libgit2"]}
-walkdir = "2"
-inquire = "0.5.2"
@@ -22,0 +15,5 @@ pkg-config = "0.3.26"
+
+
+aa
+aa
+aa
\ No newline at end of file
[process_review_changes] diffmap = …
```

Add file and hunk deletion filter

---

vibi-dpu/src/core/github/setup.rs
vibi-dpu/src/db/prs.rs
vibi-dpu/src/github/auth.rs
vibi-dpu/src/github/config.rs
vibi-dpu/src/github/prs.rs
vibi-dpu/src/github/webhook.rs
vibi-dpu/src/pubsub/listener.rs

added process_webhook_callback functionality

---

vibi-dpu/src/db/prs.rs
vibi-dpu/src/pubsub/listener.rs

addressed pr comments

---

vibi-dpu/src/core/review.rs

created different functions to create and save review object for github and bitbucket

---

vibi-dpu/src/core/review.rs
vibi-dpu/src/db/repo.rs

created different functions to create and save review object for github and bitbucket 

---

vibi-dpu/src/db/repo.rs

added more debug logs

---

vibi-dpu/src/pubsub/listener.rs

minor fix: removed a duplicate variable definition.

---

cloudbuild-prod.yaml

changed pem file name in cloudbuild

---

cloudbuild-prod.yaml

Add latest tag to image and push

---

vibi-dpu/src/bitbucket/repo.rs
vibi-dpu/src/core/coverage.rs
vibi-dpu/src/core/github/setup.rs
vibi-dpu/src/core/utils.rs
vibi-dpu/src/db/aliases.rs
vibi-dpu/src/db/mod.rs
vibi-dpu/src/utils/aliases.rs
vibi-dpu/src/utils/mod.rs

Please check the action items covered in the PR - 
Corresponding vibinex-server PR - [https://github.com/Alokit-Innovations/vibinex-server/pull/242](https://github.com/Alokit-Innovations/vibinex-server/pull/242)
This is what the comment looks like now. In this case, vibinex-server had gh login info for tapish303@gmail.com but not for other two aliases -

Get email map and fix comment and auto assign

---

vibi-dpu/src/core/approval.rs
vibi-dpu/src/core/coverage.rs
vibi-dpu/src/core/review.rs
vibi-dpu/src/db/hunk.rs
vibi-dpu/src/db/review.rs
vibi-dpu/src/utils/review.rs

Save coverage in review object in db

---

vibi-dpu/src/bitbucket/auth.rs
vibi-dpu/src/core/approval.rs
vibi-dpu/src/core/mod.rs
vibi-dpu/src/core/review.rs
vibi-dpu/src/core/utils.rs
vibi-dpu/src/db/github/auth.rs
vibi-dpu/src/github/auth.rs
vibi-dpu/src/github/config.rs
vibi-dpu/src/utils/gitops.rs

Merge tr/fixAuthFunc

---

vibi-dpu/src/core/approval.rs
vibi-dpu/src/db/prs.rs
vibi-dpu/src/github/prs.rs

Get reviewer handle fixes

---

vibi-dpu/src/core/approval.rs
vibi-dpu/src/utils/coverage.rs

Add approval comment text

---

vibi-dpu/src/core/relevance.rs

Changed function and variable names in dpu-comment-bug-fix

---

vibi-dpu/src/core/approval.rs
vibi-dpu/src/core/mod.rs
vibi-dpu/src/core/relevance.rs
vibi-dpu/src/utils/coverage.rs

Fix approval comment text

---

vibi-dpu/src/core/trigger.rs

Retrieve access token for trigger message

---

vibi-dpu/src/db/review.rs

Add check to avoid panicking main thread

---

vibi-dpu/src/core/trigger.rs

Remove redundant review object

---

vibi-dpu/src/core/relevance.rs

Add info log for repo config

---

vibi-dpu/src/core/bitbucket/setup.rs
vibi-dpu/src/core/utils.rs
vibi-dpu/src/github/repos.rs

Implement user selection of repos for bitbucket

---

vibi-dpu/src/bitbucket/config.rs
vibi-dpu/src/bitbucket/repo.rs

Remove redundant logs and call to save_repo_to_db

---

vibi-dpu/src/core/github/setup.rs
vibi-dpu/src/core/trigger.rs
vibi-dpu/src/db/repo.rs
vibi-dpu/src/github/repos.rs
vibi-dpu/src/main.rs
vibi-dpu/src/pubsub/listener.rs
vibi-dpu/src/utils/mod.rs
vibi-dpu/src/utils/parsing.rs

Parse pat repos in pubsub messages

---

vibi-dpu/src/core/github/setup.rs

removed `to_lowercase()` from github pat

---

vibi-dpu/src/core/github/setup.rs
vibi-dpu/src/core/utils.rs
vibi-dpu/src/github/webhook.rs
vibi-dpu/src/logger/init.rs
vibi-dpu/src/main.rs
vibi-dpu/src/pubsub/listener.rs
vibi-dpu/src/utils/gitops.rs

Fix logs for github pat flow

---

vibi-dpu/src/core/github/setup.rs
vibi-dpu/src/core/utils.rs
vibi-dpu/src/github/webhook.rs
vibi-dpu/src/main.rs
vibi-dpu/src/utils/gitops.rs

Fix github app logs

---

Dockerfile

Add command for creating config directory for auth

---

vibi-dpu/src/bitbucket/webhook.rs
vibi-dpu/src/core/bitbucket/setup.rs
vibi-dpu/src/db/prs.rs
vibi-dpu/src/db/user.rs
vibi-dpu/src/pubsub/listener.rs

Fix logs and convert indent to tabs

---

vibi-dpu/src/core/review.rs
vibi-dpu/src/github/auth.rs
vibi-dpu/src/main.rs
vibi-dpu/src/utils/gitops.rs

Add log fixes

---

vibi-dpu/src/github/auth.rs
vibi-dpu/src/main.rs

Fixed access token retrieval for Github App flow

---

vibi-dpu/src/logger/init.rs

changed log level from `info` to `debug`

---

user-deploy-cloud-pat-script.sh

Revert log level in cloud pat to info

---

vibi-dpu/Cargo.toml
vibi-dpu/src/core/relevance.rs

Lower number of relevant authors for comment

---

.gitmodules

add prompts repository as a submodule at the root level of this repo

---

vibi-dpu/Cargo.toml
vibi-dpu/src/graph/function_call.rs
vibi-dpu/src/graph/graph_edges.rs

Remove import identification

---

vibi-dpu/Cargo.toml
vibi-dpu/src/graph/graph_edges.rs

Revert line num text in graph
